@startuml
'https://plantuml.com/object-diagram


object Frivillig {
}
object Vagt {
}
object Bod {
}
object DataHandlerBod {
}
object DataHandlerFrivillig {
}

/' Herunder kommer pile '/

DataHandlerFrivillig "1   "-->"*" Frivillig
Bod "1" o-- "1" DataHandlerFrivillig
Bod "1  " o-- " * " Vagt
DataHandlerBod "1" -left-> "*" Bod
Vagt " *" ..> "1  " Frivillig




@enduml