@startuml
'https://plantuml.com/object-diagram


object Frivillig {
}
object Vagt {
}
object Bod {
}
object DataHandlerBod {
}
object DataHandlerFrivillig {
}

/' Herunder kommer pile '/

DataHandlerFrivillig "1"-up->"         *" Frivillig
Bod "1" o-down- "     1" DataHandlerFrivillig
Bod "1" o-right- "*" Vagt
DataHandlerBod "1" --> "*" Bod
Vagt " *" ..> "1" Frivillig




@enduml